version: '3.3'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/La_Paz
      - SERVERURL=181.188.157.3 # optional
      - SERVERPORT=51820 # optional
      - PEERS=5 # optional
      - PEERDNS=8.8.8.8 # optional
      - INTERNAL_SUBNET=10.13.13.0 # optional
      - ALLOWEDIPS=0.0.0.0/0 # optional
      - PERSISTENTKEEPALIVE_PEERS= # optional
      - LOG_CONFS=true # optional
    ports:
      - 51820:51820/udp
    volumes:
      - /root/projects/wireguard-vpn/config:/config
      - /lib/modules:/lib/modules # optional
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
